Results of doctest builder run on 2020-03-10 12:23:18
=====================================================

Document: index
---------------
**********************************************************************
File "../py2store/base.py", line ?, in default
Failed example:
    s = Store()
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[0]>", line 1, in <module>
        s = Store()
    NameError: name 'Store' is not defined
**********************************************************************
File "../py2store/base.py", line ?, in default
Failed example:
    s['foo'] = 33
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[1]>", line 1, in <module>
        s['foo'] = 33
    NameError: name 's' is not defined
**********************************************************************
File "../py2store/base.py", line ?, in default
Failed example:
    s['bar'] = 65
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[2]>", line 1, in <module>
        s['bar'] = 65
    NameError: name 's' is not defined
**********************************************************************
File "../py2store/base.py", line ?, in default
Failed example:
    assert list(s.items()) == [('foo', 33), ('bar', 65)]
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[3]>", line 1, in <module>
        assert list(s.items()) == [('foo', 33), ('bar', 65)]
    NameError: name 's' is not defined
**********************************************************************
File "../py2store/base.py", line ?, in default
Failed example:
    assert list(s.store.items()) == [('foo', 33), ('bar', 65)]  # see that the store contains the same thing
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[4]>", line 1, in <module>
        assert list(s.store.items()) == [('foo', 33), ('bar', 65)]  # see that the store contains the same thing
    NameError: name 's' is not defined
**********************************************************************
File "../py2store/base.py", line ?, in default
Failed example:
    class MyStore(Store):
        def _id_of_key(self, k):
            return k.upper()
        def _key_of_id(self, _id):
            return _id.lower()
        def _data_of_obj(self, obj):
            return chr(obj)
        def _obj_of_data(self, data):
            return ord(data)
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[6]>", line 1, in <module>
        class MyStore(Store):
    NameError: name 'Store' is not defined
**********************************************************************
File "../py2store/base.py", line ?, in default
Failed example:
    s = MyStore(store=dict())  # note that you don't need to specify dict(), since it's the default
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[7]>", line 1, in <module>
        s = MyStore(store=dict())  # note that you don't need to specify dict(), since it's the default
    NameError: name 'MyStore' is not defined
**********************************************************************
File "../py2store/base.py", line ?, in default
Failed example:
    test_store(s)
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[8]>", line 1, in <module>
        test_store(s)
    NameError: name 's' is not defined
**********************************************************************
File "../py2store/base.py", line ?, in default
Failed example:
    class MyStore(Store):
        def __init__(self, store, _id_of_key, _key_of_id, _data_of_obj, _obj_of_data):
            super().__init__(store)
            self._id_of_key = _id_of_key
            self._key_of_id = _key_of_id
            self._data_of_obj = _data_of_obj
            self._obj_of_data = _obj_of_data
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[9]>", line 1, in <module>
        class MyStore(Store):
    NameError: name 'Store' is not defined
**********************************************************************
File "../py2store/base.py", line ?, in default
Failed example:
    s = MyStore(dict(),
                _id_of_key=lambda k: k.upper(),
                _key_of_id=lambda _id: _id.lower(),
                _data_of_obj=lambda obj: chr(obj),
                _obj_of_data=lambda data: ord(data))
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[10]>", line 1, in <module>
        s = MyStore(dict(),
    NameError: name 'MyStore' is not defined
**********************************************************************
File "../py2store/base.py", line ?, in default
Failed example:
    test_store(s)
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[11]>", line 1, in <module>
        test_store(s)
    NameError: name 's' is not defined
**********************************************************************
File "../py2store/base.py", line ?, in default
Failed example:
    class MyStore(Mixin, Store):  # note that the Mixin must come before Store in the mro
        pass
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[13]>", line 1, in <module>
        class MyStore(Mixin, Store):  # note that the Mixin must come before Store in the mro
    NameError: name 'Store' is not defined
**********************************************************************
File "../py2store/base.py", line ?, in default
Failed example:
    s = MyStore()  # no dict()? No, because default anyway
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[14]>", line 1, in <module>
        s = MyStore()  # no dict()? No, because default anyway
    NameError: name 'MyStore' is not defined
**********************************************************************
File "../py2store/base.py", line ?, in default
Failed example:
    test_store(s)
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[15]>", line 1, in <module>
        test_store(s)
    NameError: name 's' is not defined
**********************************************************************
File "../py2store/base.py", line ?, in default
Failed example:
    s = Store(dict())
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[16]>", line 1, in <module>
        s = Store(dict())
    NameError: name 'Store' is not defined
**********************************************************************
File "../py2store/base.py", line ?, in default
Failed example:
    s._id_of_key=lambda k: k.upper()
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[17]>", line 1, in <module>
        s._id_of_key=lambda k: k.upper()
    NameError: name 's' is not defined
**********************************************************************
File "../py2store/base.py", line ?, in default
Failed example:
    s._key_of_id=lambda _id: _id.lower()
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[18]>", line 1, in <module>
        s._key_of_id=lambda _id: _id.lower()
    NameError: name 's' is not defined
**********************************************************************
File "../py2store/base.py", line ?, in default
Failed example:
    s._data_of_obj=lambda obj: chr(obj)
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[19]>", line 1, in <module>
        s._data_of_obj=lambda obj: chr(obj)
    NameError: name 's' is not defined
**********************************************************************
File "../py2store/base.py", line ?, in default
Failed example:
    s._obj_of_data=lambda data: ord(data)
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[20]>", line 1, in <module>
        s._obj_of_data=lambda data: ord(data)
    NameError: name 's' is not defined
**********************************************************************
File "../py2store/base.py", line ?, in default
Failed example:
    test_store(s)
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[21]>", line 1, in <module>
        test_store(s)
    NameError: name 's' is not defined
**********************************************************************
File "../py2store/core.py", line ?, in default
Failed example:
    keys = ExplicitKeys(key_collection=['foo', 'bar', 'alice'])
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[0]>", line 1, in <module>
        keys = ExplicitKeys(key_collection=['foo', 'bar', 'alice'])
    NameError: name 'ExplicitKeys' is not defined
**********************************************************************
File "../py2store/core.py", line ?, in default
Failed example:
    'foo' in keys
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[1]>", line 1, in <module>
        'foo' in keys
    NameError: name 'keys' is not defined
**********************************************************************
File "../py2store/core.py", line ?, in default
Failed example:
    'not there' in keys
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[2]>", line 1, in <module>
        'not there' in keys
    NameError: name 'keys' is not defined
**********************************************************************
File "../py2store/core.py", line ?, in default
Failed example:
    list(keys)
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[3]>", line 1, in <module>
        list(keys)
    NameError: name 'keys' is not defined
**********************************************************************
File "../py2store/core.py", line ?, in default
Failed example:
    ss = ExplicitKeysStore(s, ['d', 'a'])
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[2]>", line 1, in <module>
        ss = ExplicitKeysStore(s, ['d', 'a'])
    NameError: name 'ExplicitKeysStore' is not defined
**********************************************************************
File "../py2store/core.py", line ?, in default
Failed example:
    len(ss)
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[3]>", line 1, in <module>
        len(ss)
    NameError: name 'ss' is not defined
**********************************************************************
File "../py2store/core.py", line ?, in default
Failed example:
    list(ss)
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[4]>", line 1, in <module>
        list(ss)
    NameError: name 'ss' is not defined
**********************************************************************
File "../py2store/core.py", line ?, in default
Failed example:
    list(ss.values())
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[5]>", line 1, in <module>
        list(ss.values())
    NameError: name 'ss' is not defined
**********************************************************************
File "../py2store/core.py", line ?, in default
Failed example:
    ss.head()
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[6]>", line 1, in <module>
        ss.head()
    NameError: name 'ss' is not defined
**********************************************************************
File "../py2store/core.py", line ?, in default
Failed example:
    s = ExplicitKeysWithPrefixRelativization(key_collection=['/root/of/foo', '/root/of/bar', '/root/for/alice'])
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[1]>", line 1, in <module>
        s = ExplicitKeysWithPrefixRelativization(key_collection=['/root/of/foo', '/root/of/bar', '/root/for/alice'])
    NameError: name 'ExplicitKeysWithPrefixRelativization' is not defined
**********************************************************************
File "../py2store/core.py", line ?, in default
Failed example:
    'of/foo' in keys
Expected:
    True
Got:
    False
**********************************************************************
File "../py2store/core.py", line ?, in default
Failed example:
    list(keys)
Expected:
    ['of/foo', 'of/bar', 'for/alice']
Got:
    ['a', 'b', 'c', 'd']
**********************************************************************
1 items had failures:
  32 of  39 in default
39 tests in 1 items.
7 passed and 32 failed.
***Test Failed*** 32 failures.

Doctest summary
===============
   39 tests
   32 failures in tests
    0 failures in setup code
    0 failures in cleanup code
